### ISSUE TITLE
不知道什么时候突然就挂了

### ISSUE THREAD

**Issue by madlaxcb** [zephyrchien/ZTUN#1]
```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
Aborted

```

重新运行一段时间后 

`Segmentation fault
`

**Comment by zephyrchien** [comment]
感谢反馈，这说明目前至少存在两个问题。我检查了一下代码，发现这两个问题都出在DNS模块里面。一个是 `Query` 没有被赋予 `timeout` 函数，导致发生超时的时候调用了空的 `on_timeout()` ，然后抛出 `bad_function_call` 错误。还有一个是当DNS解析出错的时候，对空指针使用了 `freeaddrinfo()`，发生了内存错误

**Comment by zephyrchien** [comment]
尝试着修复了一下，`bad_function_call ` 应该是不会再出现了。但是可能还存在其他内存问题，我打算用内存池来彻底解决，这样也省的频繁增加/删除节点了，建立连接的延迟也会低一点
